apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-database
  description: A PostgreSQL database used by demo-service-001
  annotations:
    backstage.io/owner: team A
spec:
  type: database
  system: BKSTG-DEMO
  lifecycle: production
  owner: borixcr
  dependsOn: ['component:demo-service-001']
  resourceType: postgres
